# Generated by Django 5.1.2 on 2024-10-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imag',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modify_at',
            new_name='modified_at',
        ),
    ]
